using Kalypsis.Domain.Common;
using Kalypsis.Domain.Enums;

namespace Kalypsis.Domain.Entities;

public enum InvoiceStatus
{
    Draft     = 0,
    Issued    = 1,
    Sent      = 2,
    Paid      = 3,
    Overdue   = 4,
    Cancelled = 5
}

/// <summary>
/// A monthly invoice for one tenant. Generated by the superadmin
/// from /app/platform/billing/invoices for a chosen YYYY-MM period.
/// Lines are derived from the tenant's TenantPackageGrants at the moment
/// of generation, so editing prices after the fact does not retroactively
/// change historic invoices.
/// </summary>
public class TenantInvoice : BaseEntity
{
    public Guid TenantId { get; set; }
    public Tenant? Tenant { get; set; }

    /// <summary>Human-readable invoice number, e.g. KLP-2026-06-0001.</summary>
    public string InvoiceNumber { get; set; } = string.Empty;

    public int PeriodYear { get; set; }
    public int PeriodMonth { get; set; }

    public DateTime IssuedAt { get; set; }
    public DateTime DueAt { get; set; }
    public DateTime? SentAt { get; set; }
    public DateTime? PaidAt { get; set; }

    public InvoiceStatus Status { get; set; } = InvoiceStatus.Draft;

    public string Currency { get; set; } = "EUR";
    public decimal Subtotal { get; set; }
    /// <summary>VAT rate applied to the whole invoice, e.g. 0.24m for 24% Φ.Π.Α.</summary>
    public decimal VatRate { get; set; }
    public decimal VatAmount { get; set; }
    public decimal Total { get; set; }

    public string? Notes { get; set; }

    /// <summary>Storage key (relative path) of the generated PDF.</summary>
    public string? PdfStorageKey { get; set; }

    public ICollection<TenantInvoiceLine> Lines { get; set; } = new List<TenantInvoiceLine>();
}

public class TenantInvoiceLine : BaseEntity
{
    public Guid InvoiceId { get; set; }
    public TenantInvoice? Invoice { get; set; }

    public PackageCode Package { get; set; }

    /// <summary>Free-text description (e.g. "BackOffice — Πακέτο Back Office").</summary>
    public string Description { get; set; } = string.Empty;

    public decimal MonthlyPrice { get; set; }
    public int Quantity { get; set; } = 1;
    public decimal LineTotal { get; set; }
}
