using Kalypsis.Domain.Enums;

namespace Kalypsis.Application.Features.Customers;

public record CustomerDto(
    Guid Id,
    string CustomerNumber,
    CustomerType Type,
    CustomerStatus Status,
    string? FirstName,
    string? LastName,
    string? CompanyName,
    string? VatNumber,
    string? Email,
    string? Phone,
    string? City,
    string? Notes,
    DateTime CreatedAt,
    bool HasPortalAccount,
    DateOnly? PaymentDueDate = null,
    string? Address = null,
    string? PostalCode = null,
    DateOnly? BirthDate = null,
    string? Occupation = null,
    string? FatherName = null,
    string? MotherName = null,
    string? SpouseName = null,
    string? Nationality = null,
    string? Zone = null,
    string? ActivityCode = null,
    string? TaxOffice = null,
    string? GemiNumber = null,
    string? LegalForm = null,
    string? AltPhone = null,
    string? MobilePhone = null,
    string? Amka = null,
    string? IdNumber = null,
    string? PassportNumber = null,
    string? Region = null,
    string? Gender = null,
    string? MaritalStatus = null,
    string? Employer = null,
    string? DriverLicenseNumber = null,
    string? DriverLicenseClass = null,
    DateOnly? DriverLicenseIssueDate = null,
    DateOnly? DriverLicenseExpiryDate = null,
    string? Source = null,
    string? TagsJson = null,
    string? PhotoUrl = null);

public record CreateCustomerRequest(
    CustomerType Type,
    string? FirstName,
    string? LastName,
    string? CompanyName,
    string? VatNumber,
    string? Email,
    string? Phone,
    string? Address,
    string? City,
    string? PostalCode,
    DateOnly? BirthDate,
    string? Notes,
    bool CreatePortalAccount,
    string? Occupation = null,
    // ALIS-parity KYC fields
    string? FatherName = null,
    string? MotherName = null,
    string? SpouseName = null,
    string? Nationality = null,
    string? Zone = null,
    string? ActivityCode = null,
    CustomerStatus Status = CustomerStatus.Active,
    DateOnly? PaymentDueDate = null,
    string? TaxOffice = null,
    string? GemiNumber = null,
    string? LegalForm = null,
    string? AltPhone = null,
    string? MobilePhone = null,
    string? Amka = null,
    string? IdNumber = null,
    string? PassportNumber = null,
    string? Region = null,
    string? Gender = null,
    string? MaritalStatus = null,
    string? Employer = null,
    string? DriverLicenseNumber = null,
    string? DriverLicenseClass = null,
    DateOnly? DriverLicenseIssueDate = null,
    DateOnly? DriverLicenseExpiryDate = null,
    string? Source = null,
    string? TagsJson = null,
    string? PhotoUrl = null,
    Guid? AssignedAdvisorId = null);

public record CreateCustomerResponse(
    CustomerDto Customer,
    string? PortalEmail,
    string? PortalTemporaryPassword);
