import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, Divider, Grid, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import AutoAwesomeIcon from "@mui/icons-material/AutoAwesome";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import SmartToyIcon from "@mui/icons-material/SmartToy";
import { api } from "../api/client";

type Prompt = { id: string; name: string; purpose: string; template: string; contextScope: string; isActive: boolean };
type Run = { id: string; task: string; model: string; success: boolean; promptTokens: number; completionTokens: number; createdAt: string; error?: string; promptSummary?: string; result?: string };
type Conversation = { id: string; title: string; kind: string; promptTemplateId?: string; customerId?: string; policyId?: string; lastMessageAt?: string; status: string; messageCount: number; resultPreview?: string };
type Workbench = { prompts: Prompt[]; conversations: Conversation[]; runs: Run[]; automations: { id: string; name: string; trigger: string; isActive: boolean; actions: number }[]; storeResults: boolean };

export function IntelligenceWorkbenchPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState(0);
  const [selected, setSelected] = useState<Prompt | null>(null);
  const [name, setName] = useState(""); const [purpose, setPurpose] = useState(""); const [template, setTemplate] = useState("Ανάλυσε το {{context}} και δώσε πρακτικές επόμενες ενέργειες, χωρίς δεσμευτική ασφαλιστική ή νομική συμβουλή."); const [scope, setScope] = useState("Customer");
  const [customerId, setCustomerId] = useState(""); const [policyId, setPolicyId] = useState(""); const [override, setOverride] = useState(""); const [result, setResult] = useState("");
  const [chatId, setChatId] = useState<string>(); const [message, setMessage] = useState(""); const [chatReply, setChatReply] = useState("");
  const clearForm = () => { setSelected(null); setName(""); setPurpose(""); setTemplate("Ανάλυσε το {{context}} και δώσε πρακτικές επόμενες ενέργειες, χωρίς δεσμευτική ασφαλιστική ή νομική συμβουλή."); };
  const q = useQuery({ queryKey: ["intelligence-workbench"], queryFn: async () => (await api.get<Workbench>("/intelligence/workbench")).data });
  const save = useMutation({ mutationFn: async () => { const body = { name, purpose, template, contextScope: scope, isActive: true }; return selected ? (await api.put(`/intelligence/prompts/${selected.id}`, body)).data : (await api.post<Prompt>("/intelligence/prompts", body)).data; }, onSuccess: () => { clearForm(); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); } });
  const run = useMutation({ mutationFn: async (p: Prompt) => (await api.post<{ text?: string; error?: string }>(`/intelligence/prompts/${p.id}/run`, { customerId: customerId || null, policyId: policyId || null, promptOverride: override || null })).data, onSuccess: x => { setResult(x.text || x.error || "Δεν επιστράφηκε αποτέλεσμα."); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); } });
  const chat = useMutation({ mutationFn: async () => (await api.post<{ conversationId: string; text?: string; error?: string }>("/intelligence/chat", { conversationId: chatId || null, message, customerId: customerId || null, policyId: policyId || null })).data, onSuccess: x => { setChatId(x.conversationId); setChatReply(x.text || x.error || "Δεν επιστράφηκε απάντηση."); setMessage(""); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); } });
  const chatHistory = useQuery({ queryKey: ["intelligence-chat", chatId], enabled: !!chatId, queryFn: async () => (await api.get<{ messages: { role: string; content?: string }[] }>(`/intelligence/chats/${chatId}`)).data });
  const activePrompt = selected ?? q.data?.prompts?.[0];
  const totalTokens = useMemo(() => (q.data?.runs ?? []).reduce((a, r) => a + r.promptTokens + r.completionTokens, 0), [q.data?.runs]);
  if (q.isLoading) return <Box p={3}><Typography>Φόρτωση Intelligence workbench…</Typography></Box>;
  if (q.isError) return <Box p={3}><Alert severity="error">Δεν ήταν δυνατή η φόρτωση του workbench. Ελέγξτε τα δικαιώματα και το office AI key.</Alert></Box>;
  const data = q.data!;
  return <Box sx={{ maxWidth: 1250, mx: "auto", p: { xs: 1.5, md: 3 } }}>
    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }} gap={1} mb={2}>
      <Box><Stack direction="row" spacing={1} alignItems="center"><SmartToyIcon color="primary" /><Typography variant="h5" fontWeight={800}>AI Workbench</Typography></Stack><Typography color="text.secondary">Prompts σε πελάτες και συμβόλαια, ασφαλές ιστορικό αποτελεσμάτων, συνομιλίες και αυτοματισμοί γραφείου.</Typography></Box>
      <Stack direction="row" spacing={1}><Chip label={`${data.prompts.length} prompts`} /><Chip label={`${totalTokens.toLocaleString("el-GR")} tokens`} color="primary" variant="outlined" /></Stack>
    </Stack>
    {!data.storeResults && <Alert severity="info" sx={{ mb: 2 }}>Το ιστορικό κρατά μεταδεδομένα και χρήση tokens. Για αποθήκευση πλήρων prompts/απαντήσεων ενεργοποιήστε το «Αποθήκευση αποτελεσμάτων AI» στις ρυθμίσεις Intelligence.</Alert>}
    <Tabs value={tab} onChange={(_, v) => setTab(v)} variant="scrollable" sx={{ mb: 2 }}><Tab label="Prompt library" /><Tab label="Ιστορικό εκτελέσεων" /><Tab label="AI chat" /><Tab label="Αυτοματισμοί" /></Tabs>
    {tab === 0 && <Grid container spacing={2}>
      <Grid item xs={12} md={5}><Card><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">Τα prompts του γραφείου</Typography><Button size="small" startIcon={<AddIcon />} onClick={clearForm}>Νέο</Button></Stack><Divider sx={{ my: 1 }} />{data.prompts.length === 0 && <Typography color="text.secondary">Δεν έχει δημιουργηθεί prompt ακόμη.</Typography>}{data.prompts.map(p => <Stack key={p.id} direction="row" alignItems="center" justifyContent="space-between" sx={{ py: 1, cursor: "pointer" }} onClick={() => { setSelected(p); setName(p.name); setPurpose(p.purpose); setTemplate(p.template); setScope(p.contextScope); }}><Box><Typography fontWeight={700}>{p.name}</Typography><Typography variant="caption" color="text.secondary">{p.contextScope} · {p.purpose}</Typography></Box><Chip size="small" label={p.isActive ? "Ενεργό" : "Ανενεργό"} color={p.isActive ? "success" : "default"} /></Stack>)}</CardContent></Card></Grid>
      <Grid item xs={12} md={7}><Card><CardContent><Typography variant="h6">{selected ? "Επεξεργασία prompt" : "Νέο office prompt"}</Typography><Typography variant="body2" color="text.secondary" mb={2}>Χρησιμοποιήστε το <code>{"{{context}}"}</code> για να εισαχθούν αυτόματα τα στοιχεία του επιλεγμένου πελάτη/συμβολαίου.</Typography><Stack spacing={1.5}><TextField label="Όνομα" value={name} onChange={e => setName(e.target.value)} fullWidth /><TextField label="Σκοπός" value={purpose} onChange={e => setPurpose(e.target.value)} fullWidth /><TextField select SelectProps={{ native: true }} label="Πλαίσιο" value={scope} onChange={e => setScope(e.target.value)}><option value="General">Γενικό</option><option value="Customer">Πελάτης</option><option value="Policy">Συμβόλαιο</option><option value="Portfolio">Χαρτοφυλάκιο</option></TextField><TextField label="Prompt / οδηγίες" value={template} onChange={e => setTemplate(e.target.value)} multiline minRows={7} fullWidth /><Stack direction="row" spacing={1}><Button variant="contained" startIcon={<AddIcon />} disabled={!name.trim() || !template.trim() || save.isPending} onClick={() => save.mutate()}>Αποθήκευση</Button>{selected && <Button color="error" startIcon={<DeleteOutlineIcon />} onClick={async () => { await api.delete(`/intelligence/prompts/${selected.id}`); clearForm(); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); }}>Αρχειοθέτηση</Button>}</Stack></Stack></CardContent></Card></Grid>
      <Grid item xs={12}><Card><CardContent><Typography variant="h6" mb={1}>Εκτέλεση σε δεδομένα</Typography><Typography variant="body2" color="text.secondary" mb={2}>Βάλτε προαιρετικά τα IDs πελάτη/συμβολαίου ή αφήστε τα κενά για γενική ανάλυση. Τα δεδομένα περιορίζονται στο τρέχον γραφείο.</Typography><Grid container spacing={1.5}><Grid item xs={12} md={4}><TextField label="Customer ID (προαιρετικό)" value={customerId} onChange={e => setCustomerId(e.target.value)} fullWidth /></Grid><Grid item xs={12} md={4}><TextField label="Policy ID (προαιρετικό)" value={policyId} onChange={e => setPolicyId(e.target.value)} fullWidth /></Grid><Grid item xs={12} md={4}><TextField label="Προσωρινή οδηγία (override)" value={override} onChange={e => setOverride(e.target.value)} fullWidth /></Grid></Grid><Button sx={{ mt: 1.5 }} variant="contained" color="secondary" startIcon={<PlayArrowIcon />} disabled={!activePrompt || run.isPending} onClick={() => activePrompt && run.mutate(activePrompt)}>Εκτέλεση prompt</Button>{result && <Card variant="outlined" sx={{ mt: 2, bgcolor: "action.hover" }}><CardContent><Typography variant="subtitle2">Αποτέλεσμα</Typography><Typography sx={{ whiteSpace: "pre-wrap" }}>{result}</Typography></CardContent></Card>}</CardContent></Card></Grid>
    </Grid>}
    {tab === 1 && <Card><CardContent><Typography variant="h6" mb={1}>Ιστορικό AI</Typography>{data.runs.length === 0 && <Typography color="text.secondary">Δεν υπάρχουν εκτελέσεις.</Typography>}{data.runs.map(r => <Stack key={r.id} direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1} sx={{ py: 1, borderBottom: "1px solid", borderColor: "divider" }}><Box><Typography fontWeight={700}>{r.promptSummary || r.task} · {r.model}</Typography><Typography variant="caption" color="text.secondary">{new Date(r.createdAt).toLocaleString("el-GR")} · {r.promptTokens + r.completionTokens} tokens</Typography>{r.result && <Typography variant="body2" sx={{ mt: .5, whiteSpace: "pre-wrap" }}>{r.result}</Typography>}</Box><Chip label={r.success ? "Ολοκληρώθηκε" : "Αποτυχία"} color={r.success ? "success" : "error"} size="small" /></Stack>)}</CardContent></Card>}
    {tab === 2 && <Grid container spacing={2}><Grid item xs={12} md={8}><Card><CardContent><Typography variant="h6">Συνομιλία με το γραφείο</Typography><Typography variant="body2" color="text.secondary" mb={2}>Μπορείτε να συνδέσετε τη συνομιλία με πελάτη ή συμβόλαιο χρησιμοποιώντας τα IDs παραπάνω.</Typography>{chatHistory.data?.messages.map((m, i) => <Box key={`${m.role}-${i}`} sx={{ mb: 1, p: 1.5, borderRadius: 2, bgcolor: m.role === "assistant" ? "action.hover" : "primary.50" }}><Typography variant="caption" fontWeight={700}>{m.role === "assistant" ? "AI" : "Εσείς"}</Typography><Typography sx={{ whiteSpace: "pre-wrap" }}>{m.content}</Typography></Box>)}<TextField label="Μήνυμα" value={message} onChange={e => setMessage(e.target.value)} multiline minRows={4} fullWidth /><Button sx={{ mt: 1.5 }} variant="contained" startIcon={<AutoAwesomeIcon />} disabled={!message.trim() || chat.isPending} onClick={() => chat.mutate()}>Αποστολή</Button>{chatReply && <Box sx={{ mt: 2, p: 2, bgcolor: "action.hover", borderRadius: 2 }}><Typography sx={{ whiteSpace: "pre-wrap" }}>{chatReply}</Typography></Box>}</CardContent></Card></Grid><Grid item xs={12} md={4}><Card><CardContent><Typography variant="h6">Πρόσφατες συνομιλίες</Typography>{data.conversations.filter(x => x.kind === "Chat").map(c => <Button key={c.id} fullWidth sx={{ justifyContent: "flex-start", my: .25, textAlign: "left" }} onClick={() => { setChatId(c.id); setChatReply(""); }}><Box><Typography variant="body2">{c.title} ({c.messageCount})</Typography>{c.resultPreview && <Typography variant="caption" color="text.secondary">{c.resultPreview.slice(0, 90)}…</Typography>}</Box></Button>)}</CardContent></Card></Grid></Grid>}
    {tab === 3 && <Card><CardContent><Typography variant="h6" mb={1}>Αυτοματισμοί Intelligence</Typography><Typography color="text.secondary" mb={2}>Οι workflows του γραφείου συνεχίζουν να εκτελούνται αυτόματα. Εδώ βλέπετε τις ενεργές ροές που τροφοδοτούν ειδοποιήσεις, tasks και επικοινωνίες.</Typography>{data.automations.length === 0 && <Typography color="text.secondary">Δεν έχουν δημιουργηθεί workflows.</Typography>}{data.automations.map(a => <Stack key={a.id} direction="row" justifyContent="space-between" alignItems="center" sx={{ py: 1, borderBottom: "1px solid", borderColor: "divider" }}><Box><Typography fontWeight={700}>{a.name}</Typography><Typography variant="caption" color="text.secondary">{a.trigger} · {a.actions} ενέργειες</Typography></Box><Chip size="small" label={a.isActive ? "Ενεργό" : "Ανενεργό"} color={a.isActive ? "success" : "default"} /></Stack>)}</CardContent></Card>}
  </Box>;
}
