import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, Divider, Grid, Stack, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import SmartToyIcon from "@mui/icons-material/SmartToy";
import { Link as RouterLink } from "react-router-dom";
import { api } from "../api/client";
import { DEFAULT_PROMPT, Prompt, Workbench } from "./intelligenceWorkbenchTypes";

export function IntelligencePromptsPage() {
  const qc = useQueryClient();
  const q = useQuery({ queryKey: ["intelligence-workbench"], queryFn: async () => (await api.get<Workbench>("/intelligence/workbench")).data });
  const [selected, setSelected] = useState<Prompt | null>(null);
  const [name, setName] = useState(""); const [purpose, setPurpose] = useState(""); const [template, setTemplate] = useState(DEFAULT_PROMPT); const [scope, setScope] = useState("Customer");
  const [customerId, setCustomerId] = useState(""); const [policyId, setPolicyId] = useState(""); const [override, setOverride] = useState(""); const [result, setResult] = useState("");
  const clearForm = () => { setSelected(null); setName(""); setPurpose(""); setTemplate(DEFAULT_PROMPT); setScope("Customer"); setResult(""); };
  const save = useMutation({ mutationFn: async () => { const body = { name, purpose, template, contextScope: scope, isActive: true }; return selected ? (await api.put(`/intelligence/prompts/${selected.id}`, body)).data : (await api.post<Prompt>("/intelligence/prompts", body)).data; }, onSuccess: () => { clearForm(); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); } });
  const run = useMutation({ mutationFn: async (prompt: Prompt) => (await api.post<{ text?: string; error?: string }>(`/intelligence/prompts/${prompt.id}/run`, { customerId: customerId || null, policyId: policyId || null, promptOverride: override || null })).data, onSuccess: x => { setResult(x.text || x.error || "Δεν επιστράφηκε αποτέλεσμα."); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); } });
  if (q.isLoading) return <Box p={3}><Typography>Φόρτωση prompt library…</Typography></Box>;
  if (q.isError) return <Box p={3}><Alert severity="error">Δεν ήταν δυνατή η φόρτωση των prompts.</Alert></Box>;
  const data = q.data!;
  const activePrompt = selected ?? data.prompts[0];
  return <Box sx={{ maxWidth: 1250, mx: "auto", p: { xs: 1.5, md: 3 } }}>
    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }} gap={1} mb={2}><Box><Button component={RouterLink} to="/app/intelligence-workbench" startIcon={<ArrowBackIcon />} sx={{ px: 0 }}>AI Workbench</Button><Stack direction="row" spacing={1} alignItems="center"><SmartToyIcon color="primary" /><Typography variant="h5" fontWeight={800}>Prompt library</Typography></Stack><Typography color="text.secondary">Τα prompts του γραφείου σας, με office-scoped context και εκτέλεση σε πελάτες ή συμβόλαια.</Typography></Box><Chip label={`${data.prompts.length} prompts`} color="primary" variant="outlined" /></Stack>
    <Grid container spacing={2}>
      <Grid item xs={12} md={5}><Card><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">Τα prompts του γραφείου</Typography><Button size="small" startIcon={<AddIcon />} onClick={clearForm}>Νέο</Button></Stack><Divider sx={{ my: 1 }} />{data.prompts.length === 0 && <Typography color="text.secondary">Δεν έχει δημιουργηθεί prompt ακόμη.</Typography>}{data.prompts.map(prompt => <Stack key={prompt.id} direction="row" alignItems="center" justifyContent="space-between" sx={{ py: 1, cursor: "pointer" }} onClick={() => { setSelected(prompt); setName(prompt.name); setPurpose(prompt.purpose); setTemplate(prompt.template); setScope(prompt.contextScope); setResult(""); }}><Box><Typography fontWeight={700}>{prompt.name}</Typography><Typography variant="caption" color="text.secondary">{prompt.contextScope} · {prompt.purpose}</Typography></Box><Chip size="small" label={prompt.isActive ? "Ενεργό" : "Ανενεργό"} color={prompt.isActive ? "success" : "default"} /></Stack>)}</CardContent></Card></Grid>
      <Grid item xs={12} md={7}><Card><CardContent><Typography variant="h6">{selected ? "Επεξεργασία prompt" : "Νέο office prompt"}</Typography><Typography variant="body2" color="text.secondary" mb={2}>Χρησιμοποιήστε το <code>{"{{context}}"}</code> για να εισαχθούν αυτόματα τα στοιχεία του επιλεγμένου πελάτη ή συμβολαίου.</Typography><Stack spacing={1.5}><TextField label="Όνομα" value={name} onChange={e => setName(e.target.value)} fullWidth /><TextField label="Σκοπός" value={purpose} onChange={e => setPurpose(e.target.value)} fullWidth /><TextField select SelectProps={{ native: true }} label="Πλαίσιο" value={scope} onChange={e => setScope(e.target.value)}><option value="General">Γενικό</option><option value="Customer">Πελάτης</option><option value="Policy">Συμβόλαιο</option><option value="Portfolio">Χαρτοφυλάκιο</option></TextField><TextField label="Prompt / οδηγίες" value={template} onChange={e => setTemplate(e.target.value)} multiline minRows={7} fullWidth /><Stack direction="row" spacing={1}><Button variant="contained" startIcon={<AddIcon />} disabled={!name.trim() || !template.trim() || save.isPending} onClick={() => save.mutate()}>Αποθήκευση</Button>{selected && <Button color="error" startIcon={<DeleteOutlineIcon />} onClick={async () => { await api.delete(`/intelligence/prompts/${selected.id}`); clearForm(); void qc.invalidateQueries({ queryKey: ["intelligence-workbench"] }); }}>Αρχειοθέτηση</Button>}</Stack></Stack></CardContent></Card></Grid>
      <Grid item xs={12}><Card><CardContent><Typography variant="h6" mb={1}>Εκτέλεση prompt</Typography><Typography variant="body2" color="text.secondary" mb={2}>Τα IDs είναι προαιρετικά. Όταν δοθούν, το αποτέλεσμα χρησιμοποιεί μόνο τα δεδομένα του τρέχοντος γραφείου.</Typography><Grid container spacing={1.5}><Grid item xs={12} md={4}><TextField label="Customer ID (προαιρετικό)" value={customerId} onChange={e => setCustomerId(e.target.value)} fullWidth /></Grid><Grid item xs={12} md={4}><TextField label="Policy ID (προαιρετικό)" value={policyId} onChange={e => setPolicyId(e.target.value)} fullWidth /></Grid><Grid item xs={12} md={4}><TextField label="Προσωρινή οδηγία (override)" value={override} onChange={e => setOverride(e.target.value)} fullWidth /></Grid></Grid><Button sx={{ mt: 1.5 }} variant="contained" color="secondary" startIcon={<PlayArrowIcon />} disabled={!activePrompt || run.isPending} onClick={() => activePrompt && run.mutate(activePrompt)}>Εκτέλεση</Button>{result && <Card variant="outlined" sx={{ mt: 2, bgcolor: "action.hover" }}><CardContent><Typography variant="subtitle2">Αποτέλεσμα</Typography><Typography sx={{ whiteSpace: "pre-wrap" }}>{result}</Typography></CardContent></Card>}</CardContent></Card></Grid>
    </Grid>
  </Box>;
}
